name: simple_3d_renderer
description: Sp3dObj renderer. Includes simple cameras, light, world, and more. It also supports user taps.
version: 22.0.2
repository: https://github.com/MasahideMori-SimpleAppli/simple_3d_renderer

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  simple_3d: ^16.0.2
  util_simple_3d: ^12.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0