name: simple_3d_renderer
description: Sp3dObj renderer. Includes cameras, lights, worlds and more.
version: 2.0.0
repository: https://github.com/MasahideMori-SimpleAppli/simple_3d_renderer

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  simple_3d: ^5.0.1
  util_simple_3d: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter