name: simple_3d_renderer
description: Sp3dObj renderer. Includes simple cameras, lights, worlds, and more.
version: 16.1.0
repository: https://github.com/MasahideMori-SimpleAppli/simple_3d_renderer

environment:
  sdk: ">=2.15.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  simple_3d: ^11.1.0
  util_simple_3d: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter